export default { 
    water:"icon-agua water",
    stell:"icon-aco stell",
    dragon:"icon-dragao dragon",
    electric:"icon-eletrico electric",
    fairy:"icon-fada fairy",
    ghost:"icon-fantasma ghost",
    fire:"icon-fogo fire",
    ice:"icon-fada ice",
    bug:"icon-inseto bug",
    fighting:"icon-lutador fighting",
    normal:"icon-normal normal",
    dark:"icon-noturno dark",
    rock:"icon-pedra rock",
    grass:"icon-planta grass",
    psychic:"icon-psiquico psychic",
    ground:"icon-terrestre ground",
    poison:"icon-venenoso poison",
    flying:"icon-voador flying",
}
